name: linear-algebra
version: 0.0.0
github: ttuegel/linear-algebra

flags:
  use-int64:
    manual: True
    default: False
    description:
      Use 64-bit integers in the BLAS library interface.
      Traditionally, BLAS uses 32-bit integers, even on 64-bit platforms.
      Modern BLAS implementations may support 64-bit integers instead.

ghc-options: -Wall

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveDataTypeable
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - LambdaCase
  - MagicHash
  - MultiParamTypeClasses
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TypeFamilies
  - TypeOperators
  - UnboxedTuples
  - ViewPatterns

dependencies:
  - base
  - containers
  - equational-reasoning
  - ghc-prim
  - ghc-typelits-presburger
  - inline-c
  - parsers
  - primitive
  - template-haskell
  - transformers
  - transformers-base
  - vector

library:
  source-dirs: src/
  exposed-modules:
    - Data.Int.Blas
    - Data.Vector.Blas
    - Numeric.LinearAlgebra.Blas
  extra-libraries:
    - openblas
  when:
    - condition: flag(use-int64)
      cpp-options: -DUSE_INT64

tests:
  dblat:
    source-dirs: tests/
    main: dblat.hs
    dependencies:
      - hedgehog
      - linear-algebra
