name: linear-algebra
version: 0.0.0
github: ttuegel/linear-algebra

flags:
  use-int64:
    manual: True
    default: False
    description:
      Use 64-bit integers in the BLAS library interface.
      Traditionally, BLAS uses 32-bit integers, even on 64-bit platforms.
      Modern BLAS implementations may support 64-bit integers instead.

ghc-options: -Wall

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveDataTypeable
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TypeFamilies
  - TypeOperators

dependencies:
  - base >= 4.10
  - containers
  - inline-c
  - parsers
  - primitive
  - template-haskell
  - transformers
  - vector

library:
  source-dirs: src/
  exposed-modules:
    - Data.Int.Blas
    - Data.Vector.Blas
  extra-libraries:
    - openblas
  when:
    - condition: flag(use-int64)
      then:
        cpp-options: -DINT=int64_t
      else:
        cpp-options: -DINT=int32_t

tests:
  dblat:
    source-dirs: tests/
    main: dblat.hs
    dependencies:
      - hedgehog
      - openblas
