name: openblas
version: 0.0.0
github: ttuegel/openblas

flags:
  use-int64:
    manual: True
    default: False
    description:
      Use 64-bit integers in the BLAS library interface.
      Traditionally, BLAS uses 32-bit integers, even on 64-bit platforms.
      Modern BLAS implementations may support 64-bit integers instead.

ghc-options: -Wall

default-extensions:
  - DataKinds
  - DeriveDataTypeable
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - MultiParamTypeClasses
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TypeFamilies
  - TypeOperators

dependencies:
  - base >= 4.10
  - containers
  - inline-c
  - parsers
  - primitive
  - template-haskell
  - transformers
  - vector

library:
  source-dirs: src/
  exposed-modules:
    - Data.Dim
    - Data.Int.Blas
  extra-libraries:
    - openblas
  include-dirs:
    - include/
  when:
    - condition: flag(use-int64)
      cpp-options: -DINT=int64_t
